# Generated by Django 4.1.3 on 2022-11-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_artist_id_song_date_released_song_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
    ]
